version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: dailypod-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  celery:
    image: python:3.9-slim
    container_name: dailypod-celery
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: >
      sh -c "pip install -r requirements.txt &&
             celery -A celery_app worker --loglevel=info"
    restart: unless-stopped

  celery-beat:
    image: python:3.9-slim
    container_name: dailypod-celery-beat
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: >
      sh -c "pip install -r requirements.txt &&
             celery -A celery_app beat --loglevel=info"
    restart: unless-stopped

volumes:
  redis_data: 